/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 *********************** Configuration BOARD_FullSpeed *************************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_FullSpeed configuration
 ******************************************************************************/
#define BOARD_FULLSPEED_CORE_CLOCK                 41943040U  /*!< Core clock frequency: 41943040Hz */

/*! @brief ICS set for BOARD_FullSpeed configuration.
 */
extern const ics_config_t icsConfig_BOARD_FullSpeed;
/*! @brief SIM module set for BOARD_FullSpeed configuration.
 */
extern const sim_clock_config_t simConfig_BOARD_FullSpeed;
/*! @brief OSC set for BOARD_FullSpeed configuration.
 */
extern const osc_config_t oscConfig_BOARD_FullSpeed;

/*******************************************************************************
 * API for BOARD_FullSpeed configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_FullSpeed(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ************************ Configuration BOARD_LowPower *************************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_LowPower configuration
 ******************************************************************************/
#define BOARD_LOWPOWER_CORE_CLOCK                      8192U  /*!< Core clock frequency: 8192Hz */

/*! @brief ICS set for BOARD_LowPower configuration.
 */
extern const ics_config_t icsConfig_BOARD_LowPower;
/*! @brief SIM module set for BOARD_LowPower configuration.
 */
extern const sim_clock_config_t simConfig_BOARD_LowPower;
/*! @brief OSC set for BOARD_LowPower configuration.
 */
extern const osc_config_t oscConfig_BOARD_LowPower;

/*******************************************************************************
 * API for BOARD_LowPower configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_LowPower(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

