/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/
/*
 * How to setup clock using clock driver functions:
 *
 * 1. call CLOCK_SetSimSafeDivs() to set the system clock dividers in SIM to safe value.
 *
 * 2. If external oscillator is used Call CLOCK_SetXtal0Freq() to set XTAL0 frequency based on board settings and
 *    call CLOCK_InitOsc0() to init the OSC.
 *
 * 3. Call CLOCK_BootToXxxMode()/CLOCK_SetXxxMode() to set ICS run at the target mode.
 *
 * 4. If ICSIRCLK is needed, call CLOCK_SetInternalRefClkConfig() to enable the clock.
 *
 * 5. call CLOCK_SetSimConfig() to configure the divider in sim.
 */

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Clocks v4.0
processor: MKE04Z8xxx4
package_id: MKE04Z8VWJ4
mcu_data: ksdk2_0
processor_version: 3.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

#include "clock_config.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/

/*******************************************************************************
 * Variables
 ******************************************************************************/
/* System clock frequency. */
extern uint32_t SystemCoreClock;

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/
void BOARD_InitBootClocks(void)
{
    BOARD_LowPower();
}

/*******************************************************************************
 *********************** Configuration BOARD_FullSpeed *************************
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!Configuration
name: BOARD_FullSpeed
outputs:
- {id: Bus_clock.outFreq, value: 20.97152 MHz}
- {id: Core_clock.outFreq, value: 41.94304 MHz}
- {id: Flash_clock.outFreq, value: 20.97152 MHz}
- {id: ICSFF_clock.outFreq, value: 32.768 kHz}
- {id: LPO_clock.outFreq, value: 1 kHz}
- {id: Plat_clock.outFreq, value: 41.94304 MHz}
- {id: System_clock.outFreq, value: 41.94304 MHz}
- {id: Timer_clock.outFreq, value: 41.94304 MHz}
settings:
- {id: ICS.BDIV.scale, value: '1', locked: true}
- {id: SIM.DIV2.scale, value: '2'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Variables for BOARD_FullSpeed configuration
 ******************************************************************************/
const ics_config_t icsConfig_BOARD_FullSpeed =
    {
        .icsMode = kICS_ModeFEI,                  /* FEI - FLL Engaged Internal */
        .irClkEnableMode = 0,                     /* ICSIRCLK disabled */
        .bDiv = 0x0U,                             /* Bus clock divider: divided by 1 */
        .rDiv = 0x0U,                             /* FLL external reference clock divider: divided by 1 */
    };
const sim_clock_config_t simConfig_BOARD_FullSpeed =
    {
        .outDiv1 = 0x0U,                          /* DIV1 clock divider: divided by 1 */
        .outDiv2 = 0x1U,                          /* DIV2 clock divider: divided by 2 */
        .outDiv3 = 0x0U,                          /* DIV3 clock divider: divided by 1 */
        .busClkPrescaler = 0x0U,                  /* bus clock optional prescaler */
    };
const osc_config_t oscConfig_BOARD_FullSpeed =
    {
        .freq = 0U,                               /* Oscillator frequency: 0Hz */
        .workMode = 0,                            /* Use external clock */
        .enableMode = 0,                          /* Disable external reference clock */
    };

/*******************************************************************************
 * Code for BOARD_FullSpeed configuration
 ******************************************************************************/
void BOARD_FullSpeed(void)
{
    /* Set the system clock dividers in SIM to safe value. */
    CLOCK_SetSimSafeDivs();
    /* Set ICS to FEI mode. */
    CLOCK_BootToFeiMode(icsConfig_BOARD_FullSpeed.bDiv);
    /* Configure the Internal Reference clock (ICSIRCLK). */
    CLOCK_SetInternalRefClkConfig(icsConfig_BOARD_FullSpeed.irClkEnableMode);
    /* Set the clock configuration in SIM module. */
    CLOCK_SetSimConfig(&simConfig_BOARD_FullSpeed);
    /* Set SystemCoreClock variable. */
    SystemCoreClock = BOARD_FULLSPEED_CORE_CLOCK;
}

/*******************************************************************************
 ************************ Configuration BOARD_LowPower *************************
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!Configuration
name: BOARD_LowPower
called_from_default_init: true
outputs:
- {id: Bus_clock.outFreq, value: 8.192 kHz}
- {id: Core_clock.outFreq, value: 8.192 kHz}
- {id: Flash_clock.outFreq, value: 8.192 kHz}
- {id: LPO_clock.outFreq, value: 1 kHz}
- {id: Plat_clock.outFreq, value: 8.192 kHz}
- {id: System_clock.outFreq, value: 8.192 kHz}
- {id: Timer_clock.outFreq, value: 8.192 kHz}
settings:
- {id: ICSMode, value: FBILP}
- {id: ICS.BDIV.scale, value: '4', locked: true}
- {id: ICS.CLKS.sel, value: ICS.IRCLK}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Variables for BOARD_LowPower configuration
 ******************************************************************************/
const ics_config_t icsConfig_BOARD_LowPower =
    {
        .icsMode = kICS_ModeBILP,                 /* BILP - Bypassed Low Power Internal */
        .irClkEnableMode = 0,                     /* ICSIRCLK disabled */
        .bDiv = 0x2U,                             /* Bus clock divider: divided by 4 */
        .rDiv = 0x0U,                             /* FLL external reference clock divider: divided by 1 */
    };
const sim_clock_config_t simConfig_BOARD_LowPower =
    {
        .outDiv1 = 0x0U,                          /* DIV1 clock divider: divided by 1 */
        .outDiv2 = 0x0U,                          /* DIV2 clock divider: divided by 1 */
        .outDiv3 = 0x0U,                          /* DIV3 clock divider: divided by 1 */
        .busClkPrescaler = 0x0U,                  /* bus clock optional prescaler */
    };
const osc_config_t oscConfig_BOARD_LowPower =
    {
        .freq = 0U,                               /* Oscillator frequency: 0Hz */
        .workMode = 0,                            /* Use external clock */
        .enableMode = 0,                          /* Disable external reference clock */
    };

/*******************************************************************************
 * Code for BOARD_LowPower configuration
 ******************************************************************************/
void BOARD_LowPower(void)
{
    /* Set the system clock dividers in SIM to safe value. */
    CLOCK_SetSimSafeDivs();
    /* Set ICS to FBILP mode. */
    CLOCK_BootToBilpMode(icsConfig_BOARD_LowPower.bDiv);
    /* Configure the Internal Reference clock (ICSIRCLK). */
    CLOCK_SetInternalRefClkConfig(icsConfig_BOARD_LowPower.irClkEnableMode);
    /* Set the clock configuration in SIM module. */
    CLOCK_SetSimConfig(&simConfig_BOARD_LowPower);
    /* Set SystemCoreClock variable. */
    SystemCoreClock = BOARD_LOWPOWER_CORE_CLOCK;
}

