/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.0
processor: MKE04Z8xxx4
package_id: MKE04Z8VWJ4
mcu_data: ksdk2_0
processor_version: 3.0.0
pin_labels:
- {pin_num: '5', pin_signal: PTB7/I2C0_SCL/EXTAL, label: L2_IN}
- {pin_num: '6', pin_signal: PTB6/I2C0_SDA/XTAL, label: L1_IN}
- {pin_num: '8', pin_signal: PTB4/KBI1_P6/FTM2_CH4/SPI0_MISO/ACMP1_IN2/NMI_b, label: SW1}
- {pin_num: '9', pin_signal: PTC3/KBI1_P5/FTM2_CH3/ADC0_SE11, label: NC0}
- {pin_num: '10', pin_signal: PTC2/KBI1_P4/FTM2_CH2/ADC0_SE10, label: DBG1}
- {pin_num: '11', pin_signal: PTC1/KBI1_P3/FTM2_CH1/ADC0_SE9, label: DBG0}
- {pin_num: '12', pin_signal: PTC0/KBI1_P2/FTM2_CH0/ADC0_SE8, label: ACCEL_INTn}
- {pin_num: '16', pin_signal: PTB0/KBI0_P4/UART0_RX/SPI0_PCS0/PWT_IN1/ADC0_SE4, label: L2_uP}
- {pin_num: '19', pin_signal: PTA1/KBI0_P1/FTM0_CH1/ACMP0_IN1/ADC0_SE1, label: L1_uP}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '1', peripheral: SystemControl, signal: RESET, pin_signal: PTA5/IRQ/TCLK1/RESET_b}
  - {pin_num: '5', peripheral: GPIOA, signal: 'GPIO, 15', pin_signal: PTB7/I2C0_SCL/EXTAL}
  - {pin_num: '6', peripheral: GPIOA, signal: 'GPIO, 14', pin_signal: PTB6/I2C0_SDA/XTAL}
  - {pin_num: '14', peripheral: SPI0, signal: SCK, pin_signal: PTB2/KBI0_P6/SPI0_SCK/FTM0_CH0/ACMP0_IN0/ADC0_SE6}
  - {pin_num: '13', peripheral: SPI0, signal: MOSI, pin_signal: PTB3/KBI0_P7/SPI0_MOSI/FTM0_CH1/ADC0_SE7}
  - {pin_num: '7', peripheral: SPI0, signal: PCS, pin_signal: PTB5/KBI1_P7/FTM2_CH5/SPI0_PCS0/ACMP1_OUT}
  - {pin_num: '15', peripheral: UART0, signal: TX, pin_signal: PTB1/KBI0_P5/UART0_TX/SPI0_MISO/TCLK2/ADC0_SE5}
  - {pin_num: '18', peripheral: I2C0, signal: SDA, pin_signal: PTA2/KBI0_P2/UART0_RX/I2C0_SDA}
  - {pin_num: '17', peripheral: I2C0, signal: SCL, pin_signal: PTA3/KBI0_P3/UART0_TX/I2C0_SCL}
  - {pin_num: '19', peripheral: GPIOA, signal: 'GPIO, 1', pin_signal: PTA1/KBI0_P1/FTM0_CH1/ACMP0_IN1/ADC0_SE1}
  - {pin_num: '20', peripheral: CoreDebug, signal: SWD_CLK, pin_signal: PTA0/KBI0_P0/FTM0_CH0/RTCO/ACMP0_IN2/ADC0_SE0/SWD_CLK}
  - {pin_num: '2', peripheral: CoreDebug, signal: SWD_DIO, pin_signal: PTA4/ACMP0_OUT/SWD_DIO}
  - {pin_num: '8', peripheral: GPIOA, signal: 'GPIO, 12', pin_signal: PTB4/KBI1_P6/FTM2_CH4/SPI0_MISO/ACMP1_IN2/NMI_b}
  - {pin_num: '10', peripheral: GPIOA, signal: 'GPIO, 18', pin_signal: PTC2/KBI1_P4/FTM2_CH2/ADC0_SE10}
  - {pin_num: '11', peripheral: GPIOA, signal: 'GPIO, 17', pin_signal: PTC1/KBI1_P3/FTM2_CH1/ADC0_SE9}
  - {pin_num: '12', peripheral: GPIOA, signal: 'GPIO, 16', pin_signal: PTC0/KBI1_P2/FTM2_CH0/ADC0_SE8}
  - {pin_num: '16', peripheral: GPIOA, signal: 'GPIO, 8', pin_signal: PTB0/KBI0_P4/UART0_RX/SPI0_PCS0/PWT_IN1/ADC0_SE4}
  - {pin_num: '9', peripheral: GPIOA, signal: 'GPIO, 19', pin_signal: PTC3/KBI1_P5/FTM2_CH3/ADC0_SE11}
  - {pin_num: '3', peripheral: SUPPLY, signal: 'VDD, 0', pin_signal: VDD}
  - {pin_num: '3', peripheral: ADC, signal: VDDA, pin_signal: VDDA/VREFH}
  - {pin_num: '4', peripheral: ADC, signal: VREFL, pin_signal: VREFL}
  - {pin_num: '4', peripheral: SUPPLY, signal: 'VSS, 0', pin_signal: VSSA/VSS}
  - {pin_num: '3', peripheral: ADC, signal: VREFH, pin_signal: VDDA/VREFH}
  - {pin_num: '4', peripheral: ADC, signal: VSSA, pin_signal: VSSA/VSS}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* pin 18,17 is configured as I2C0_SDA, I2C0_SCL */
    PORT_SetPinSelect(kPORT_I2C0, kPORT_I2C0_SCLPTA3_SDAPTA2);
    /* pin 14,7,13 is configured as SPI0_SCK, SPI0_PCS0, SPI0_MOSI */
    PORT_SetPinSelect(kPORT_SPI0, kPORT_SPI0_SCKPTB2_MOSIPTB3_MISOPTB4_PCSPTB5);
    /* pin 15 is configured as UART0_TX */
    PORT_SetPinSelect(kPORT_UART0, kPORT_UART0_RXPTB0_TXPTB1);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
